### ISSUE TITLE
Animated elements doesn't rendering in development environment

### ISSUE THREAD

**Issue by igorviniciussantana** [morellodev/react-awesome-reveal#186] opened 2023-09-22 11:40 UTC
Hi!
I using the library with nextjs 13.5.2 and when I run ```npm run dev``` the elements doesn't showing up, but when I run ```npm run build``` everything works. I think this problem is happening because of the incompatibility with SSR, but in the docs it says that the library supports SSR.

The Website in development environment

![image](https://github.com/morellodev/react-awesome-reveal/assets/86114583/50ed3819-1517-47d3-bfdd-776350c0f5bd)

The Website in production
![image](https://github.com/morellodev/react-awesome-reveal/assets/86114583/c3689de0-b9d6-4991-b849-0f3d15818c4d)

The link of the repo
https://github.com/igorviniciussantana/selene-website

**Comment by alay-patel** [comment] 2023-10-03 09:57
Same issue . Please suggest fix or alternative.

**Comment by DMOEdetc** [comment] 2023-10-08 17:29
I can confirm this. Works on 13.4.x but not 13.5.x. It adds "opacitiy:0" as intended, but does not start the animation.

**Comment by janhoeck** [comment] 2023-10-09 12:18
Same here.

**Comment by samueldlacruz** [comment] 2023-10-17 02:32
Same here

**Comment by SidrahR** [comment] 2023-10-24 16:14
Same issue. Any workaround to use with Next.js 13.5?

**Comment by CarlessoMauricio** [comment] 2023-10-26 21:07
same here

**Comment by Mr-Nobody-li** [comment] 2023-10-27 09:24
same here

**Comment by directlycrazy** [comment] 2023-10-27 11:01
This may be related to react-intersection-observer events not firing on the latest Next version, causing this to not work either. We may just have to wait until it is patched upstream. https://github.com/thebuilder/react-intersection-observer/issues/649 https://github.com/thebuilder/react-intersection-observer/discussions/647

**Comment by DMOEdetc** [comment] 2023-10-28 18:26
The Problem stays with 14.0.0 the same.

**Comment by thebuilder** [comment] 2023-11-01 12:56
- Are any warnings/errors logged?
- Are the pages/components correctly marked as `'use client'`?

This library is also missing the `'use client'` directive. Might that be the problem?
https://unpkg.com/browse/react-awesome-reveal@4.2.6/dist/index.js

**Comment by DMOEdetc** [comment] 2023-11-01 19:39
> * Are any warnings/errors logged?
> 
>     * Are the pages/components correctly marked as `'use client'`?
> 
> 
> This library is also missing the `'use client'` directive. Might that be the problem? https://unpkg.com/browse/react-awesome-reveal@4.2.6/dist/index.js

Here is a small example. The 'use client' seems to be no problem at all. The higher level component is marked as client component. It works perfectly with next 13.4.x, but not with any higher version.

[Example in codesandbox.io](https://codesandbox.io/p/sandbox/sweet-bush-ywtt2m?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clog5dnll000c2a6acap652wh%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clog5dnll00032a6aepvx7pfl%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clog5dnll00092a6af42o4ja6%2522%257D%252C%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clog5ms61034p2a6afwbleetz%2522%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clog5dnll000b2a6aqsxqt3si%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clog5dnll00032a6aepvx7pfl%2522%253A%257B%2522id%2522%253A%2522clog5dnll00032a6aepvx7pfl%2522%252C%2522activeTabId%2522%253A%2522clog5ewjq00ed2a6az4ny48br%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clog5dnlk00022a6agns1139v%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fapp%252Fexample.tsx%2522%252C%2522id%2522%253A%2522clog5ewjq00ed2a6az4ny48br%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fapp%252Fpage.tsx%2522%252C%2522id%2522%253A%2522clog5ey8p00fz2a6an36ijxgn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522id%2522%253A%2522clog5nzef03kn2a6a4txedyso%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clog5dnll000b2a6aqsxqt3si%2522%253A%257B%2522id%2522%253A%2522clog5dnll000b2a6aqsxqt3si%2522%252C%2522activeTabId%2522%253A%2522clog5peht03vf2a6a038v4vbl%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clog5peht03vf2a6a038v4vbl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clog5dnll00092a6af42o4ja6%2522%253A%257B%2522id%2522%253A%2522clog5dnll00092a6af42o4ja6%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clog5dnll00042a6agi55q6yw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clog5dnll00052a6anyhuo76q%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522build%2522%257D%252C%257B%2522id%2522%253A%2522clog5dnll00072a6ace8nkad9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522lint%2522%257D%252C%257B%2522id%2522%253A%2522clog5dnll00082a6ayxq19yzu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522install%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522yarn%2520add%2520next%254014.0.1%2522%252C%2522id%2522%253A%2522clog5dxz4006u2a6a0hgiaphz%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522yarn%2520add%2520react%254018.2.0%2522%252C%2522id%2522%253A%2522clog5e3o1008g2a6a828jri54%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522yarn%2520add%2520react-awesome-reveal%25404.2.6%2522%252C%2522id%2522%253A%2522clog5efbc00a22a6a3zz32y1v%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clog5dnll00052a6anyhuo76q%2522%257D%252C%2522clog5ms61034p2a6afwbleetz%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clog5mg9k034l2a6adkg818ks%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clog5mrgy00a4edge3e0w98g4%2522%257D%255D%252C%2522id%2522%253A%2522clog5ms61034p2a6afwbleetz%2522%252C%2522activeTabId%2522%253A%2522clog5mg9k034l2a6adkg818ks%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by thebuilder** [comment] 2023-11-01 21:45
Thanks for the example - Just want to confirm the problem isn't related to [react-intersection-observer](https://github.com/thebuilder/react-intersection-observer/issues/649).

Tried adding a `useInView` to the [sandbox](https://codesandbox.io/p/sandbox/sweet-bush-ywtt2m?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clog5dnll000c2a6acap652wh%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clog5dnll00032a6aepvx7pfl%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clog5dnll00092a6af42o4ja6%2522%257D%252C%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clog5ms61034p2a6afwbleetz%2522%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clog5dnll000b2a6aqsxqt3si%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60.114453021027416%252C39.885546978972584%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clog5dnll00032a6aepvx7pfl%2522%253A%257B%2522id%2522%253A%2522clog5dnll00032a6aepvx7pfl%2522%252C%2522activeTabId%2522%253A%2522clog5ewjq00ed2a6az4ny48br%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clog5dnlk00022a6agns1139v%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fapp%252Fexample.tsx%2522%252C%2522id%2522%253A%2522clog5ewjq00ed2a6az4ny48br%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fapp%252Fpage.tsx%2522%252C%2522id%2522%253A%2522clog5ey8p00fz2a6an36ijxgn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522id%2522%253A%2522clog5nzef03kn2a6a4txedyso%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clog5dnll000b2a6aqsxqt3si%2522%253A%257B%2522id%2522%253A%2522clog5dnll000b2a6aqsxqt3si%2522%252C%2522activeTabId%2522%253A%2522clog5peht03vf2a6a038v4vbl%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clog5peht03vf2a6a038v4vbl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clog5dnll00092a6af42o4ja6%2522%253A%257B%2522id%2522%253A%2522clog5dnll00092a6af42o4ja6%2522%252C%2522activeTabId%2522%253A%2522clog5dnll00042a6agi55q6yw%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clog5dnll00042a6agi55q6yw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clog5dnll00052a6anyhuo76q%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522build%2522%257D%252C%257B%2522id%2522%253A%2522clog5dnll00072a6ace8nkad9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522lint%2522%257D%252C%257B%2522id%2522%253A%2522clog5dnll00082a6ayxq19yzu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522install%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522yarn%2520add%2520next%254014.0.1%2522%252C%2522id%2522%253A%2522clog5dxz4006u2a6a0hgiaphz%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522yarn%2520add%2520react%254018.2.0%2522%252C%2522id%2522%253A%2522clog5e3o1008g2a6a828jri54%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522yarn%2520add%2520react-awesome-reveal%25404.2.6%2522%252C%2522id%2522%253A%2522clog5efbc00a22a6a3zz32y1v%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522yarn%2520add%2520react-intersection-observer%25409.5.2%2522%252C%2522id%2522%253A%2522cloga892w01s83b6kxcdwalql%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clog5ms61034p2a6afwbleetz%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clog5mg9k034l2a6adkg818ks%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clog5mrgy00a4edge3e0w98g4%2522%257D%255D%252C%2522id%2522%253A%2522clog5ms61034p2a6afwbleetz%2522%252C%2522activeTabId%2522%253A%2522clog5mg9k034l2a6adkg818ks%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D), and it works as expected.

**Comment by DMOEdetc** [comment] 2023-11-03 10:42
> `useInView`

Can you provide an example? So react react-awesome-reveal could be updated :)

**Comment by CarlessoMauricio** [comment] 2023-11-07 05:25
any update guys?

**Comment by MaximeDetaille** [comment] 2023-11-07 22:07
I got the exact same problem on Next14 on simple landing page do you have a workaround ?

**Comment by DMOEdetc** [comment] 2023-11-08 19:05
> I got the exact same problem on Next14 on simple landing page do you have a workaround ?

Sadly: Not yet, and i don't have much time currently to search for a fix :/

**Comment by thebuilder** [comment] 2023-11-08 23:33
Had a second look. It looks like it might be the `<InView>` component that's failing after the change in Next.js. 
If anybody has insights into what can cause it, that would be helpful.

https://github.com/thebuilder/react-intersection-observer/issues/649
https://stackblitz.com/edit/stackblitz-starters-ubcjsa?file=app%2Fpage.tsx

**Closed** 2023-11-13 13:54 UTC
