### ISSUE TITLE
Typescript child type?

### ISSUE THREAD

**Issue by EliotSlevin** [morellodev/react-awesome-reveal#188] opened 2023-10-14 13:52 UTC
I'm very confused what the type of children passed to reveal components should be. E.g. consider this typescript code

```
import { Fade } from 'react-awesome-reveal'
export const Wrapper = ({ children }: { children: React.ReactNode }) => (
    <Fade>
        {children}
    </Fade>
)
```

Typescript will throw the following error on <Fade>
```
Type '{ children: ReactNode; }' has no properties in common with type 'IntrinsicAttributes & FadeProps'.ts(2559)
```

Digging through the source, at its core reveal's components are built on React.FC, so I don't get why this doesn't work. I've tried React.Element and JSX.Element too.

**Comment by morellodev** [comment] 2023-10-14 15:14
Do you have a [reproducible example](https://codesandbox.io/s/react-awesome-reveal-typescript-177uom?file=/src/App.tsx) on CodeSandbox? My tests are all passing without issues.

**Comment by morellodev** [comment] 2023-10-30 08:25
Closing this due to lack of a reproducible example

**Closed by morellodev** 2023-10-30 08:25 UTC
